[
  { id: 1, name: 'Mandiri' },
  { id: 2, name: 'BRI' },
  { id: 3, name: 'BNI' },
  { id: 4, name: 'BCA' },
  { id: 5, name: 'BSI (Bank Syariah Indonesia)' },
  { id: 6, name: 'CIMB Niaga/CIMB Niaga Syariah' },
  { id: 7, name: 'Muamalat' },
  { id: 8, name: 'Danamon / Danamon Syariah' },
  { id: 9, name: 'Bank Permata' },
  { id: 10, name: 'Maybank Indonesia' },
  { id: 11, name: 'Panin Bank' },
  { id: 12, name: 'TMRW/UOB' },
  { id: 13, name: 'OCBC NISP' },
  { id: 14, name: 'Citibank' },
  { id: 15, name: 'Bank Artha Graha Internasional' },
  { id: 16, name: 'Bank of Tokyo Mitsubishi UFJ' },
  { id: 17, name: 'DBS Indonesia' },
  { id: 18, name: 'Standard Chartered Bank' },
  { id: 19, name: 'Bank Capital Indonesia' },
  { id: 20, name: 'ANZ Indonesia' },
  { id: 21, name: 'Bank of China (Hong Kong) Limited' },
  { id: 22, name: 'Bank Bumi Arta' },
  { id: 23, name: 'HSBC Indonesia' },
  { id: 24, name: 'Rabobank International Indonesia' },
  { id: 25, name: 'Bank Mayapada' },
  { id: 26, name: 'BJB' },
  { id: 27, name: 'Bank DKI Jakarta' },
  { id: 28, name: 'BPD DIY' },
  { id: 29, name: 'Bank Jateng' },
  { id: 30, name: 'Bank Jatim' },
  { id: 31, name: 'Bank Jambi' },
  { id: 32, name: 'Bank Sumut' },
  { id: 33, name: 'Bank Sumbar (Bank Nagari)' },
  { id: 34, name: 'Bank Riau Kepri' },
  { id: 35, name: 'Bank Sumsel Babel' },
  { id: 36, name: 'Bank Lampung' },
  { id: 37, name: 'Bank Kalsel' },
  { id: 38, name: 'Bank Kalbar' },
  { id: 39, name: 'Bank Kaltimtara' },
  { id: 40, name: 'Bank Kalteng' },
  { id: 41, name: 'Bank Sulselbar' },
  { id: 42, name: 'Bank SulutGo' },
  { id: 43, name: 'Bank NTB Syariah' },
  { id: 44, name: 'BPD Bali' },
  { id: 45, name: 'Bank NTT' },
  { id: 46, name: 'Bank Maluku' },
  { id: 47, name: 'Bank Papua' },
  { id: 48, name: 'Bank Bengkulu' },
  { id: 49, name: 'Bank Sulteng' },
  { id: 50, name: 'Bank Sultra' },
  { id: 51, name: 'Bank Nusantara Parahyangan' },
  { id: 52, name: 'Bank of India Indonesia' },
  { id: 53, name: 'Bank Mestika Dharma' },
  { id: 54, name: 'Bank Sinarmas' },
  { id: 55, name: 'Bank Maspion Indonesia' },
  { id: 56, name: 'Bank Ganesha' },
  { id: 57, name: 'ICBC Indonesia' },
  { id: 58, name: 'QNB Indonesia' },
  { id: 59, name: 'BTN' },
  { id: 60, name: 'Bank Woori Saudara' },
  { id: 61, name: 'BTPN / Jenius / BTPN Wow!' },
];
